# Configuration for Tomcat Server Embedded

server:
  port: 7777

# Configuration for Postgresql JDBC

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/testdb_01
    username: postgres
    password: 1234
    driver-class-name: org.postgresql.Driver

# Configuration for Postgresql Hibernate

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

# Configuration for Spring Security

#logging:
#  level:
#    org.springframework.security: TRACE
